### ISSUE TITLE
Provide usage and requirements

### ISSUE THREAD

**Issue by DaereanLegrand** [praveena2j/RCMA#2]
Hi,

Always expecting you to be having a good day. I'm a UG student from Perú for my final project I'm evaluating techniques in order to implement my own. Truthfully I do not know how to start running the code in this repository, would you be able to provide some simple instructions or just give us the requirements.txt?

Thanks in advance.

**Comment by praveena2j** [comment]
Sure I will update the readme file and requirements file soon
